# Generated by Django 2.2.3 on 2019-07-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carstation', '0002_auto_20190730_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carstation',
            old_name='adress',
            new_name='address',
        ),
    ]
