# Generated by Django 2.2.3 on 2019-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstation', '0003_auto_20190730_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstation',
            name='lengtitude',
            field=models.DecimalField(decimal_places=10, default=True, max_digits=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carstation',
            name='longtitude',
            field=models.DecimalField(decimal_places=10, default=3, max_digits=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carstation',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='carstation',
            name='bookings',
            field=models.DecimalField(decimal_places=10, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='carstation',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
